# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assumptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installers_start', models.IntegerField(default=1)),
                ('installers_weekly_growth', models.FloatField(default=0.1)),
                ('deal_frequency_in_weeks', models.IntegerField(default=8)),
                ('deal_latency_in_weeks', models.IntegerField(default=4)),
                ('deal_revenue_thousands', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installers_current', models.FloatField()),
                ('installers_count', models.IntegerField()),
                ('deals_count', models.IntegerField()),
                ('deals_revenue', models.IntegerField()),
                ('deals_revenue_cumulative', models.IntegerField()),
                ('assumptions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Assumptions')),
            ],
        ),
    ]
