# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly',
            name='week_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='weekly',
            name='deals_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weekly',
            name='deals_revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weekly',
            name='deals_revenue_cumulative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weekly',
            name='installers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weekly',
            name='installers_current',
            field=models.FloatField(default=0.0),
        ),
    ]
