# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_auto_20160217_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='assumptions',
            name='target_monthly_revenue',
            field=models.IntegerField(default=20),
        ),
    ]
